---
- hosts: all
  tasks:
    - name: Remove a file, if present
      copy:
        content: ""
        dest: ~kongadxr/.ssh/known_hosts
        force: no
        owner: kongadxr
        group: kongadxr
        mode: 0600

    - name: fetch the public ssh key
      shell: cat ~/.ssh/id_rsa.pub
      register: ssh_keys

    - name: deploy the ihss key on storage node {{ hc4t05928.itcs.hpecorp.net }}
      authorized_key:
        user: kongadxr
        key: "{{ ssh_keys.stdout }}"
      delegate_to: hc4t05928.itcs.hpecorp.net

    - name: Adding an entry in the known_hosts file for {{ hc4t05928.itcs.hpecorp.net }}
      shell: |
        ssh-keyscan -t rsa,dsa hc4t05928.itcs.hpecorp.net >> ~kongadxr/.ssh/known_hosts

    - name: Adding an entry in the known_hosts file for {{ hc4t05928.itcs.hpecorp.net }}
      shell: |
        ssh-keyscan -t rsa,dsa hc4t05928.itcs.hpecorp.net >> ~kongadxr/.ssh/known_hosts


    - name: deploy the ihss key on storage node {{ hc4t05929.itcs.hpecorp.net }}
      authorized_key:
        user: kongadxr
        key: "{{ ssh_keys.stdout }}"
      delegate_to: hc4t05929.itcs.hpecorp.net


    - name: Adding an entry in the known_hosts file for {{ hc4t05929.itcs.hpecorp.net }}
      shell: |
          ssh-keyscan -t rsa,dsa hc4t05929.itcs.hpecorp.net >> ~kongadxr/.ssh/known_hosts

      when:
      become: true
      become_user: "kongadxr"

