---
- hosts: devops
  become: yes
  become_user: root  
  tasks:
  - name: write the apache config file
    copy:
      src: index.html
      dest: /var/www/html
    notify:
    - restart apache

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
